# Generated by Django 6.0 on 2025-12-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lobace_Food_User_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
