# Generated by Django 6.0 on 2025-12-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobace_Food_User_App', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
