# Generated by Django 6.0 on 2025-12-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobace_Food_User_App', '0003_customuser_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
